//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Google Analytics Code: Code for google analytics
		///</summary>
		[ImplementPropertyType("analyticsCode")]
		public string AnalyticsCode
		{
			get { return this.GetPropertyValue<string>("analyticsCode"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// Facebook Stream
		///</summary>
		[ImplementPropertyType("facebookStream")]
		public object FacebookStream
		{
			get { return this.GetPropertyValue("facebookStream"); }
		}

		///<summary>
		/// Favicon and touch icons: This image will be used for your website favicon and device bookmarks. We suggest that you use an image of at least 310x310 pixels.
		///</summary>
		[ImplementPropertyType("faviconAndTouchIcons")]
		public object FaviconAndTouchIcons
		{
			get { return this.GetPropertyValue("faviconAndTouchIcons"); }
		}

		///<summary>
		/// Github
		///</summary>
		[ImplementPropertyType("github")]
		public string Github
		{
			get { return this.GetPropertyValue<string>("github"); }
		}

		///<summary>
		/// Google+
		///</summary>
		[ImplementPropertyType("google")]
		public string Google
		{
			get { return this.GetPropertyValue<string>("google"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		///<summary>
		/// Instagram Stream
		///</summary>
		[ImplementPropertyType("instagramStream")]
		public object InstagramStream
		{
			get { return this.GetPropertyValue("instagramStream"); }
		}

		///<summary>
		/// LinkedIn
		///</summary>
		[ImplementPropertyType("linkedin")]
		public string Linkedin
		{
			get { return this.GetPropertyValue<string>("linkedin"); }
		}

		///<summary>
		/// Phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return this.GetPropertyValue<string>("phoneNumber"); }
		}

		///<summary>
		/// Skype Username
		///</summary>
		[ImplementPropertyType("skypeUsername")]
		public string SkypeUsername
		{
			get { return this.GetPropertyValue<string>("skypeUsername"); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}

		///<summary>
		/// Twitter Stream
		///</summary>
		[ImplementPropertyType("twitterStream")]
		public object TwitterStream
		{
			get { return this.GetPropertyValue("twitterStream"); }
		}
	}
}
